openapi: 3.0.3
info:
  title: UE INFIRMARY REST API
  description: UE INFIRMARY REST API
  version: 1.0.0
servers:
  - url: https://localapi.uerm.edu.ph:8081
paths:
  /infirmary/ape/printout/visit-pdf-token:
    post:
      summary: Get access token to view APE printout PDF
      description: Get access token to view APE printout PDF
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Access Token (valid for 15 minutes)
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Request body is malformed.
        "401":
          description: Username or password is incorrect.
        "500":
          description: Server Error
  /infirmary/ape/printout/visit-pdf:
    get:
      summary: View APE printout PDF
      description: View APE printout PDF
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accessToken:
                  type: string
                patientCode:
                  type: string
                  description: Employee/Student number of the patient.
                schoolYear:
                  type: integer
                  description: School Year when the patient visited (optional, will get last APE result if available)
                  minimum: 2024
                  maximum: 2500
      responses:
        "200":
          description: PDF File
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        "400":
          description: Request body is malformed.
        "401":
          description: Access token is invalid or expired.
        "500":
          description: Server Error
